server:
  port: 8083

spring:
  application:
    name: incident-intelligence-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

