server:
  address: 0.0.0.0
  port: ${PORT:8082}

spring:
  application:
    name: healing-engine

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
